import type { Field } from "@/components/ui/form";

/** Field configs for every add/edit form. Options mirror the constants in the schema. */
const P = ["critical", "high", "medium", "low"] as const;

export const FIELDS: Record<string, Field[]> = {
  tasks: [
    { name: "title", label: "Task", required: true, placeholder: "Follow up with James and review offer" },
    { name: "priority", label: "Priority", type: "select", options: P, half: true, default: "medium" },
    { name: "category", label: "Category", type: "select", options: ["client_follow_up", "prospecting", "listing", "buyer", "escrow", "marketing", "administrative", "personal"], half: true, default: "client_follow_up" },
    { name: "dueDate", label: "Due date", type: "date", half: true },
    { name: "dueTime", label: "Due time", type: "time", half: true },
    { name: "contactId", label: "Related client", type: "contact", half: true },
    { name: "propertyId", label: "Related property", type: "property", half: true },
    { name: "transactionId", label: "Related transaction", type: "transaction", half: true },
    { name: "recurrence", label: "Repeats", type: "select", options: ["none", "daily", "weekly", "monthly"], half: true, default: "none" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  calls: [
    { name: "contactId", label: "Client", type: "contact", required: true },
    { name: "scheduledDate", label: "Date", type: "date", half: true },
    { name: "scheduledTime", label: "Time", type: "time", half: true },
    { name: "priority", label: "Priority", type: "select", options: P, half: true, default: "medium" },
    { name: "reason", label: "Reason for call", half: true, placeholder: "Offer strategy, new listing…" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  contacts: [
    { name: "firstName", label: "First name", required: true, half: true },
    { name: "lastName", label: "Last name", half: true },
    { name: "phone", label: "Phone", half: true, placeholder: "(949) 555-0100" },
    { name: "email", label: "Email", half: true },
    { name: "type", label: "Contact type", type: "select", options: ["buyer", "seller", "past_client", "lead", "agent", "vendor", "sphere"], half: true, default: "lead" },
    { name: "leadSource", label: "Lead source", type: "select", options: ["referral", "past_client", "instagram", "open_house", "cold_outreach", "agent_referral", "website", "zillow", "off_market", "sphere", "other"], half: true, default: "referral" },
    { name: "spouse", label: "Spouse / partner", half: true },
    { name: "birthday", label: "Birthday", type: "date", half: true },
    { name: "homeAddress", label: "Home address" },
    { name: "priceMin", label: "Price range from", type: "money", half: true },
    { name: "priceMax", label: "Price range to", type: "money", half: true },
    { name: "preferredAreas", label: "Preferred areas", type: "list", placeholder: "Newport Coast, Laguna Beach" },
    { name: "currentProperty", label: "Current property", half: true },
    { name: "tags", label: "Tags", type: "list", half: true },
    { name: "stage", label: "Pipeline stage", type: "select", options: ["new_lead", "contacted", "qualified", "active_buyer", "active_seller", "showing_homes", "listing_appointment", "offer_submitted", "negotiating", "in_escrow", "closed", "nurture"], half: true, default: "new_lead" },
    { name: "probability", label: "Probability", type: "percent", half: true, default: 20 },
    { name: "estValue", label: "Est. transaction value", type: "money", half: true },
    { name: "estCommission", label: "Est. commission", type: "money", half: true },
    { name: "nextAction", label: "Next action", half: true },
    { name: "nextFollowUpAt", label: "Next follow-up", type: "date", half: true },
    { name: "checkBackAt", label: "Check back on", type: "date", half: true, help: "For “check back in X months”" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  buyers: [
    { name: "contactId", label: "Contact", type: "contact", required: true },
    { name: "temperature", label: "Temperature", type: "select", options: ["hot", "warm", "nurture"], half: true, default: "warm" },
    { name: "priority", label: "Priority", type: "select", options: P, half: true, default: "medium" },
    { name: "priceMin", label: "Price from", type: "money", half: true },
    { name: "priceMax", label: "Price to", type: "money", half: true },
    { name: "targetAreas", label: "Target areas", type: "list" },
    { name: "minBeds", label: "Min bedrooms", type: "number", half: true },
    { name: "minBaths", label: "Min bathrooms", type: "number", half: true },
    { name: "minSqft", label: "Min square feet", type: "number", half: true },
    { name: "propertyType", label: "Property type", type: "select", options: ["Single Family", "Condo", "Townhome", "Land", "Multi-Family"], half: true },
    { name: "lotRequirements", label: "Lot requirements" },
    { name: "mustHaves", label: "Must-haves", type: "list", placeholder: "ocean view, office, pool" },
    { name: "dealBreakers", label: "Deal breakers", type: "list", placeholder: "interior courtyard, busy street" },
    { name: "financingType", label: "Financing", half: true },
    { name: "preApprovalAmount", label: "Pre-approval amount", type: "money", half: true },
    { name: "timeline", label: "Preferred timeline", half: true, placeholder: "Next 60 days" },
    { name: "status", label: "Search status", type: "select", options: ["active", "paused", "closed"], half: true, default: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  sellers: [
    { name: "contactId", label: "Contact", type: "contact", required: true },
    { name: "propertyAddress", label: "Property address", half: true },
    { name: "city", label: "City", half: true },
    { name: "estimatedValue", label: "Estimated home value", type: "money", half: true },
    { name: "expectedListPrice", label: "Expected list price", type: "money", half: true },
    { name: "stage", label: "Stage", type: "select", options: ["lead", "contacted", "appointment_scheduled", "preparing_home", "agreement_signed", "coming_soon", "active", "sold"], half: true, default: "lead" },
    { name: "probability", label: "Probability of listing", type: "percent", half: true, default: 30 },
    { name: "timeline", label: "Timeline", half: true },
    { name: "motivation", label: "Motivation", half: true },
    { name: "listingAppointmentAt", label: "Listing appointment", type: "datetime", half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  properties: [
    { name: "address", label: "Address", required: true },
    { name: "city", label: "City", half: true },
    { name: "zip", label: "ZIP", half: true },
    { name: "beds", label: "Bedrooms", type: "number", half: true },
    { name: "baths", label: "Bathrooms", type: "number", half: true },
    { name: "sqft", label: "Square feet", type: "number", half: true },
    { name: "lotSqft", label: "Lot (sq ft)", type: "number", half: true },
    { name: "propertyType", label: "Type", type: "select", options: ["Single Family", "Condo", "Townhome", "Land", "Multi-Family"], half: true, default: "Single Family" },
    { name: "yearBuilt", label: "Year built", type: "number", half: true },
    { name: "view", label: "View / features", placeholder: "Ocean view, pool, office" },
    { name: "photoUrl", label: "Photo URL" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  listings: [
    { name: "propertyId", label: "Property", type: "property", required: true },
    { name: "sellerContactId", label: "Seller", type: "contact" },
    { name: "listPrice", label: "List price", type: "money", required: true, half: true },
    { name: "commissionPct", label: "Commission", type: "percent", half: true, default: 2.5 },
    { name: "status", label: "Status", type: "select", options: ["coming_soon", "off_market", "active", "price_improvement", "offer_received", "in_negotiation", "in_escrow", "closed", "withdrawn"], half: true, default: "active" },
    { name: "listedAt", label: "Listing date", type: "date", half: true },
    { name: "showings", label: "Showings", type: "number", half: true, default: 0 },
    { name: "offers", label: "Offers", type: "number", half: true, default: 0 },
    { name: "openHouses", label: "Open houses", type: "number", half: true, default: 0 },
    { name: "nextAction", label: "Next action", half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  transactions: [
    { name: "propertyId", label: "Property", type: "property", required: true },
    { name: "contactId", label: "Client", type: "contact", half: true },
    { name: "side", label: "Representing", type: "select", options: [{ value: "buyer", label: "Buyer" }, { value: "seller", label: "Seller" }, { value: "both", label: "Both sides" }], half: true, default: "buyer" },
    { name: "status", label: "Status", type: "select", options: ["escrow", "closed", "cancelled"], half: true, default: "escrow" },
    { name: "purchasePrice", label: "Purchase price", type: "money", required: true, half: true },
    { name: "commissionPct", label: "Commission", type: "percent", half: true, default: 2.5 },
    { name: "brokerSplitPct", label: "Team / broker split", type: "percent", half: true, default: 68 },
    { name: "referralFee", label: "Referral fee", type: "money", half: true, default: 0 },
    { name: "expenses", label: "Expenses", type: "money", half: true, default: 0 },
    { name: "escrowOpenedAt", label: "Escrow opened", type: "date", half: true },
    { name: "closingDate", label: "Closing date", type: "date", half: true },
    { name: "leadSource", label: "Lead source", type: "select", options: ["referral", "past_client", "instagram", "open_house", "cold_outreach", "agent_referral", "website", "zillow", "off_market", "sphere", "other"], half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  offers: [
    { name: "contactId", label: "Buyer", type: "contact", half: true },
    { name: "propertyId", label: "Property", type: "property", half: true },
    { name: "listPrice", label: "List price", type: "money", half: true },
    { name: "offerPrice", label: "Offer price", type: "money", required: true, half: true },
    { name: "sellerCounter", label: "Seller counter", type: "money", half: true },
    { name: "currentOffer", label: "Current offer", type: "money", half: true },
    { name: "status", label: "Status", type: "select", options: ["preparing", "submitted", "countered", "accepted", "rejected", "backup", "withdrawn"], half: true, default: "preparing" },
    { name: "submittedAt", label: "Date submitted", type: "date", half: true },
    { name: "financing", label: "Financing", half: true },
    { name: "downPayment", label: "Down payment", type: "money", half: true },
    { name: "closingTimeline", label: "Closing timeline", half: true },
    { name: "contingencies", label: "Contingencies", type: "list", half: true, placeholder: "Inspection 10d, Appraisal, Loan 17d" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  appointments: [
    { name: "title", label: "Title", required: true },
    { name: "type", label: "Type", type: "select", options: ["showing", "listing_appointment", "buyer_consultation", "open_house", "inspection", "appraisal", "final_walkthrough", "closing", "client_follow_up", "personal"], half: true, default: "showing" },
    { name: "location", label: "Location", half: true },
    { name: "startsAt", label: "Starts", type: "datetime", required: true, half: true },
    { name: "endsAt", label: "Ends", type: "datetime", half: true },
    { name: "contactId", label: "Client", type: "contact", half: true },
    { name: "propertyId", label: "Property", type: "property", half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  notes: [
    { name: "body", label: "Note", type: "textarea", required: true, placeholder: "Seller at 123 Main may list in October." },
    { name: "contactId", label: "Contact", type: "contact", half: true },
    { name: "propertyId", label: "Property", type: "property", half: true },
    { name: "transactionId", label: "Transaction", type: "transaction", half: true },
    { name: "pinned", label: "Pin", type: "checkbox", half: true, help: "Keep at the top" },
  ],
  opportunities: [
    { name: "address", label: "Address", required: true },
    { name: "area", label: "Area", half: true },
    { name: "kind", label: "Type", type: "select", options: ["off_market", "coming_soon", "pocket_listing", "tear_down", "investment"], half: true, default: "off_market" },
    { name: "expectedPrice", label: "Expected price", type: "money", half: true },
    { name: "status", label: "Status", type: "select", options: ["new", "watching", "pursuing", "matched", "dead"], half: true, default: "new" },
    { name: "beds", label: "Beds", type: "number", half: true },
    { name: "baths", label: "Baths", type: "number", half: true },
    { name: "sqft", label: "Sq ft", type: "number", half: true },
    { name: "propertyType", label: "Property type", type: "select", options: ["Single Family", "Condo", "Townhome", "Land", "Multi-Family"], half: true },
    { name: "sourceAgent", label: "Source / agent", half: true },
    { name: "contactId", label: "Contact", type: "contact", half: true },
    { name: "notes", label: "Notes", type: "textarea", placeholder: "Ocean view, pool — keywords here feed buyer matching" },
  ],
  touchpoints: [
    { name: "contactId", label: "Contact", type: "contact", required: true },
    { name: "kind", label: "Touch", type: "select", options: ["birthday", "anniversary", "gift", "holiday", "quarterly", "home_value", "referral_request"], half: true, default: "quarterly" },
    { name: "dueDate", label: "Due", type: "date", required: true, half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  milestones: [
    { name: "name", label: "Milestone", required: true, half: true },
    { name: "dueDate", label: "Due", type: "date", half: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const ENTITY_LABEL: Record<string, string> = { tasks: "Task", calls: "Call", contacts: "Contact", buyers: "Buyer", sellers: "Seller", properties: "Property", listings: "Listing", transactions: "Transaction", offers: "Offer", appointments: "Appointment", notes: "Note", opportunities: "Opportunity", touchpoints: "Touchpoint", milestones: "Milestone" };
