import { chromium, devices } from "playwright";
import assert from "node:assert/strict";
import path from "node:path";
const base = process.env.TEST_URL || "http://127.0.0.1:3100";
if (!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base)) throw new Error("Only an isolated localhost test server is supported.");
const browser = await chromium.launch({ headless: true, channel: process.env.TEST_BROWSER_CHANNEL || (process.platform === "win32" ? "msedge" : undefined) });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
const page = await context.newPage();
page.on("pageerror", (e) => errors.push(e.message));
page.setDefaultTimeout(30000);
const read = (url) => page.evaluate(async (url) => { const r = await fetch(url); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }, url);
const order = (group) => page.locator(`[data-group="${group}"]`).evaluateAll((els) => els.map((e) => e.dataset.sortable));
try {
  await page.goto(base + "/integrations");
  await page.getByRole("button", { name: "Save & connect vault", exact: true }).waitFor();
  const status = await read("/api/integrations/status");
  assert.ok(status.obsidian.dir?.endsWith("realtorpro-browser-vault"), "Refusing to test against a personal vault/workspace");
  assert.equal(status.claude.configured, false, "Test server must not have a real Claude connection");
  assert.equal(status.obsidian.allowClaude, false);
  await page.getByLabel("Your name", { exact: true }).fill("Test Agent");
  const savedProfile = page.waitForResponse((r) => /\/api\/settings\//.test(r.url()) && r.request().method() === "PATCH");
  await page.getByRole("button", { name: "Save profile", exact: true }).click();
  assert.equal((await savedProfile).status(), 200);
  assert.equal((await read("/api/settings")).items[0].agentName, "Test Agent");
  const records = await read("/api/contacts");
  assert.ok(records.items.every((c) => c.email === "browser-test@example.com"), "Refusing to mutate a workspace with personal records");
  await page.getByRole("button", { name: "Import typed notes", exact: true }).click();
  await page.getByRole("button", { name: "Import into the command center", exact: true }).waitFor();
  assert.equal((await read("/api/contacts")).count, records.count, "Preview must not write contacts");
  const applied = page.waitForResponse((r) => r.url().endsWith("/api/import/apply") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Import into the command center", exact: true }).click();
  assert.equal((await applied).status(), 200);
  const contacts = await read("/api/contacts");
  assert.equal(contacts.count, 1);
  assert.equal(contacts.items[0].email, "browser-test@example.com");
  assert.equal((await read("/api/buyers")).count, 1);
  assert.ok((await read("/api/backups")).backups.length > 0);
  await page.reload();
  await page.getByRole("button", { name: "Disconnect vault", exact: true }).waitFor();
  assert.equal((await read("/api/integrations/status")).obsidian.exists, true);
  console.log("PASS vault connection persists; preview → approval → contact + buyer + backup");
  await page.screenshot({ path: path.resolve("../../outputs/realtorpro-hardening-connections.png"), fullPage: true });
  const backupResponse = page.waitForResponse((r) => r.url().endsWith("/api/backups") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Create backup now", exact: true }).click();
  const snapshot = await (await backupResponse).json();
  await page.getByRole("combobox", { name: "Restore an existing snapshot", exact: true }).selectOption(snapshot.id);
  await page.getByLabel("Type RESTORE to continue", { exact: true }).fill("RESTORE");
  const restoreResponse = page.waitForResponse((r) => r.url().endsWith("/api/backups") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Restore selected backup", exact: true }).click();
  assert.equal((await restoreResponse).status(), 200);
  assert.equal((await read("/api/contacts")).count, 1);
  console.log("PASS profile settings and browser backup/restore with typed confirmation");

  await page.goto(base + "/");
  await page.getByRole("button", { name: "Arrange dashboard", exact: true }).click();
  const before = await order("kpis");
  const handle = page.locator(`[data-sortable="${before[0]}"] .drag-handle`);
  const target = page.locator(`[data-sortable="${before[2]}"]`);
  const a = await handle.boundingBox(), b = await target.boundingBox();
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2);
  await page.mouse.down();
  await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 12 });
  await page.mouse.up();
  const swapped = [...before]; [swapped[0], swapped[2]] = [swapped[2], swapped[0]];
  assert.deepEqual(await order("kpis"), swapped, "Mouse drag must swap tiles");
  await page.reload();
  await page.getByRole("button", { name: "Arrange dashboard", exact: true }).waitFor();
  assert.deepEqual(await order("kpis"), swapped, "Layout must survive refresh");
  await page.getByRole("button", { name: "Arrange dashboard", exact: true }).click();
  await page.locator(`[data-sortable="${swapped[0]}"] .drag-handle`).focus();
  await page.keyboard.press("ArrowRight");
  assert.equal((await order("kpis"))[1], swapped[0], "Keyboard move must work");
  const cards = await order("cards");
  await page.locator(`[data-sortable="${cards[0]}"] .layout-buttons button`).last().click();
  assert.equal((await order("cards"))[1], cards[0], "Card move button must work");
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  assert.deepEqual(await order("kpis"), before);
  assert.deepEqual(await order("cards"), cards);
  await page.screenshot({ path: path.resolve("../../outputs/realtorpro-hardening-arrange.png"), fullPage: true });
  console.log("PASS desktop mouse swap, keyboard, card buttons, refresh persistence and reset");

  const mobile = await browser.newContext({ ...devices["iPhone 13"] });
  const phone = await mobile.newPage();
  phone.on("pageerror", (e) => errors.push(e.message));
  await phone.goto(base + "/");
  await phone.getByRole("button", { name: "Arrange dashboard", exact: true }).click();
  const getMobileOrder = () => phone.locator('[data-group="kpis"]').evaluateAll((els) => els.map((e) => e.dataset.sortable));
  const initial = await getMobileOrder();
  const mh = await phone.locator(`[data-sortable="${initial[0]}"] .drag-handle`).boundingBox();
  const mt = await phone.locator(`[data-sortable="${initial[1]}"]`).boundingBox();
  const cdp = await mobile.newCDPSession(phone);
  const sx = mh.x + mh.width / 2, sy = mh.y + mh.height / 2;
  const ex = mt.x + mt.width / 2, ey = mt.y + mt.height / 2;
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: sx, y: sy, id: 1 }] });
  for (let i = 1; i <= 10; i++) await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: sx + (ex - sx) * i / 10, y: sy + (ey - sy) * i / 10, id: 1 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  assert.equal((await getMobileOrder())[1], initial[0], "Touch drag must swap tiles");
  await phone.screenshot({ path: path.resolve("../../outputs/realtorpro-hardening-mobile.png") });
  console.log("PASS touch-device drag with real browser touch input");

  const unauth = await browser.newContext();
  assert.equal((await unauth.request.get(base + "/api/contacts")).status(), 401);
  const crossSite = await page.evaluate(async () => (await fetch("/api/import/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bundle: { contacts: [] } }) })).status);
  assert.equal(crossSite, 422, "Unreviewed bundle must not apply");
  assert.deepEqual(errors, [], "No browser JavaScript exceptions");
  console.log("PASS authentication and unreviewed-import rejection; no browser exceptions");
} finally { await browser.close(); }
